// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6D9D1qKbsv3szr1OCazyQrh6B65dxNTw',
    appId: '1:294101503496:web:6473799b9d0fb949704bbd',
    messagingSenderId: '294101503496',
    projectId: 'market-app-f1213',
    authDomain: 'market-app-f1213.firebaseapp.com',
    storageBucket: 'market-app-f1213.appspot.com',
    measurementId: 'G-0X4NDVCSYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBeLnDjYiWf7TMOu4xB9at4HC3jgeDQbE',
    appId: '1:294101503496:android:ca2abacc6d4e3667704bbd',
    messagingSenderId: '294101503496',
    projectId: 'market-app-f1213',
    storageBucket: 'market-app-f1213.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5y9WpNpKEicURTSJjmKhvbaxNdLZ8QJ8',
    appId: '1:294101503496:ios:4fd5b8ccc7543c11704bbd',
    messagingSenderId: '294101503496',
    projectId: 'market-app-f1213',
    storageBucket: 'market-app-f1213.appspot.com',
    iosBundleId: 'com.example.market',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5y9WpNpKEicURTSJjmKhvbaxNdLZ8QJ8',
    appId: '1:294101503496:ios:15feef935488e776704bbd',
    messagingSenderId: '294101503496',
    projectId: 'market-app-f1213',
    storageBucket: 'market-app-f1213.appspot.com',
    iosBundleId: 'com.example.market.RunnerTests',
  );
}
